- README.md
- contracts/SwapFactory.sol
- contracts/Swaplace.sol
- contracts/interfaces/ISwap.sol
- contracts/interfaces/ISwapFactory.sol
- contracts/interfaces/ITransfer.sol
Refactored the name of the variable amountOrCallOrId into just amountOrId
closes #16
> refactor: of the amountOrCallOrId variable, where the call is removed because is not being used

- contracts/SwapFactory.sol
- contracts/interfaces/ISwapFactory.sol
- test/TestSwaplace.test.ts
- test/TestTradeFactory.test.ts
- test/utils/SwapFactory.ts
- test/utils/utils.ts
- delete composeSwap from contracts
- create composeSwap on lib
- adapt all tests using composeSwap
- created utils.ts
- created swapfactory.ts
close #15
> refactor: compose swap on the contract side is not necessary as it can be delegate to the implementer

- contracts/SwapFactory.sol
- contracts/interfaces/IErrors.sol
- removed the function call error as it doesn't exist anymore
- added natspec descriptions to the errors interface
- added the library and the implementation to swap factory
close #39
> refactor: remove unnecessary custom errors from SwapFactory and import the error interface

- test/TestSwaplace.test.ts
- test/TestTradeFactory.test.ts
- test/utils/utils.ts
- added a method for getting block timestamp in `utils.ts`
- changed the timestamp approach from the tests into calling the utils lib
close #42
> feat: fetch current timestamp of hardhat network session and add to utils script

- .prettierrc.yml
closes #122 
.prettiererc added to the root directory with the following properties:
`.prettierrc.yml`
```
trailingComma: "es5"
tabWidth: 4
semi: false
singleQuote: true
```
> feat: adding .prettierc to the root directory

- contracts/Swaplace.sol
- contracts/echidna/TestSwaplace.sol
- test/TestSwaplace.test.ts
closes #120 
- I renamed the `swapId` inside `Swaplace.sol` to `_totalSwaps`
- I added the `totalSwaps` getter function at the end of the `Swaplace.sol` smart contract.
- I used NatSpec format to write a brief description for the function
- I renamed the `swapId` calls inside `TestSwaplace.test.ts` and `TestSwaplace.sol` to `totalSwaps`
Obs: In order to successfully run `yarn test` I had to improve the hardhat's solidity version to `0.8.20` due to the new interfaces inside the mock folder added previously, but I am not pushing the hardhat changes. Should I do it?
> refactor: `swapId` variable changed to `_totalSwaps` / `totalSwaps` getter function added 

- contracts/Swaplace.sol
- Renamed swaps into _swaps
- Removed the comment within the code
- Changed the variable name from l_swapId into swapId
> refactor: local variable name

- hardhat.config.ts
GitHub is not correctly fetching vars from the environment when Pull Requests are testing with actions.
This is a temporary solution until we find out why.
closes #145
> fix: hardcoding deployer address to config

- README.md
If you suggest more thing to add :)
> doc: [ISSUE-137] Update readme

- contracts/SwapFactory.sol
- contracts/Swaplace.sol
- contracts/interfaces/ISwaplace.sol
- docs/SwapFactory.md
- docs/Swaplace.md
- docs/interfaces/ISwaplace.md
- scripts/acceptSwap.ts
- scripts/cancelSwap.ts
- scripts/getSwap.ts
- changed id on comments into ID uppercase
- changed id into swapId
This is being proposed to preserve legibility across the code and avoid confusion
> refactor: changed id variable into swapId

- contracts/Swaplace.sol
- contracts/interfaces/ISwaplace.sol
- docs/interfaces/ISwaplace.md
- test/TestSwaplace.test.ts
closes #121 
- Example:
```
uint256 startGas = gasleft();
// code
gasUsed = startGas - gasleft();
```
- In the document I separeted a comparison about the options to emit events :)
- When we call the "createSwap" event with the current parameters (id, owner and expiry) the gas usage is 1932.
```
event SwapCreated(
uint256 indexed id,
address indexed owner,
uint256 indexed expiry
);
```
```
emit SwapCreated(swapId, msg.sender, swap.expiry);
```
- But we can optimize with assembly, so the gas usage can be: 1919
```
//keccak-256(SwapCreated(uint256,address,uint256))
bytes32 private constant EVENT_SWAP_CREATED_SIGNATURE =
0xecac413765eac3982e66e569ad3a200e6b3f188ac4d7d44cc5da667779ca8d05;
```
```
uint256 swapExpiry = swap.expiry;
assembly {
log4(0x00, 0x00, EVENT_SWAP_CREATED_SIGNATURE, …
```
> [ISSUE-121] docs: research gas and cost efficiency for event emission

- README.md
- contracts/SwapFactory.sol
- contracts/Swaplace.sol
- contracts/echidna/TestSwapFactory.sol
- contracts/interfaces/ISwap.sol
- contracts/interfaces/ISwapFactory.sol
- test/TestSwapFactory.test.ts
- test/TestSwaplace.test.ts
- test/utils/SwapFactory.ts
> refactor: using bitwise operations to save gas #104 

- test/TestSwapFactory.test.ts
- test/TestSwaplace.test.ts
- test/utils/SwapFactory.ts
Proposing a fix for the overall legibility of timestamp when using the `config` feature of the contract
Changed `expiry` of block.timestamp into `currentTimestamp`. 
`expiry` is now the return variable of the `parseData(swap.config)`
> refactor: fixing legibility of timestamp

- contracts/Swaplace.sol
> refactor: sloads and increments in assembly for gas optimization. #179

- contracts/Swaplace.sol
- contracts/interfaces/ISwaplace.sol
- test/TestSwaplace.test.ts
>  refactor: drastically lowering cancelSwap gas consumption #181 

- contracts/Swaplace.sol
>  refactor: Set the value of config as zero directly instead of packing allowed and expiry in the acceptSwap(). #184 

- contracts/Swaplace.sol
- contracts/interfaces/ISwaplace.sol
- test/TestSwaplace.test.ts
> refactor: events must emit addresses involved in the operation for better dApp indexing #186

- contracts/Swaplace.sol
- test/TestSwaplace.test.ts
>  fix: incorrect event emission on acceptSwap #194 

- hardhat.config.ts
- Trying to fix hardcoded solution to solve workflow vars issue not been recognized (failed - read last comment)
- Removed random choice of networks and kept most used ones (eth and polygon)
- Added optimizer
- Added max contract size to true
- Added default hardhat chain id
(please don't judge my commit names, I'm ashamed)
> refactor: hardhat configs pre-subgraph

- package.json
>  refactor: repo scripts section #197

- Makefile
- scripts/createSwap.ts
- scripts/deploy.ts
- scripts/deployMock.ts
- scripts/mint.ts
- Changing the comment description of `make transaction` script on Makefile.
- Adding `wait tx.wait()` to wait transactions to be mined to not mess up the script sequence when saving on `.env` and risking script continuation without the right parameters.
> fix: comment on make transactions and add transaction mined period

- .env.sample
- contracts/mock/MockERC721.sol
- hardhat.config.ts
> feat: Kakarot rpc and ipfs on mockerc721

- scripts/approve.ts
- scripts/mint.ts
> refactor: ERC1155 to be minted and approved 

- scripts/deployMock.ts
> refactor: Includes ERC1155 mock to be deployed

- test/TestSwaplace.test.ts
> test: Created unit tests to implement native ethers transfer 

- contracts/SwapFactory.sol
- contracts/Swaplace.sol
- contracts/interfaces/IErrors.sol
- contracts/interfaces/ISwapFactory.sol
- test/TestSwaplace.test.ts
> refactor: reverts when owner wrongly sends ethers 

- hardhat.config.ts
closes #229 
Updated from Mumbai to AMOY
Added - OPSEPOLIA (OPTMISM) 
Added - FUJI (AVALANCHE) 
Added - BASE SEPOLIA
Added - BNB TESTNET
Added - ARBITRUM SEPOLIA
> feat: Updated and added new networks to the `hardhat.config.ts` 

- docs/solidity-docgen/interfaces/ISwaplace.md
Added some missing tables text in the `ISwaplace.md` file generated by docgen
> fix: added missing tables in the docs
