contracts/SwapFactory.sol, contracts/Swaplace.sol, hardhat.config.ts
Successfully changed the title of the contract.
close #5
=> docs: refactor the natspec title of the swaplace contract

contracts/Swaplace.sol, contracts/interfaces/IErrors.sol
=> add: interface for contract errors

contracts/Swaplace.sol
=> fix: revoke address zero check from createSwap

contracts/SwapFactory.sol, contracts/Swaplace.sol, contracts/interfaces/ISwapFactory.sol, test/TestSwaplace.test.ts, test/TestTradeFactory.test.ts
=> update: expiry using off-chain calculation

contracts/Swaplace.sol
=> fix: wrong variable passed to custom error in createSwap

contracts/SwapFactory.sol, contracts/Swaplace.sol, contracts/interfaces/ISwapFactory.sol, contracts/interfaces/ISwaplace.sol, contracts/interfaces/ITransfer.sol
=> docs: include NatSpec for each function

contracts/SwapFactory.sol, contracts/Swaplace.sol
- fixed whitespace in main contract
- changed natspec title
=> docs: enhance the natspec title of the SwapFactory contract

contracts/SwapFactory.sol, test/utils/SwapFactory.ts
- removed the check from the SwapFactory.sol
- removed the check from the SwapFactory.ts
close #46
=> fix: unnecessary check for address zero in swap factory and utils

contracts/Swaplace.sol
- removed the error library
- removed the error implementation
close #51
=> fix: linearization of inheritance graph of error interface

contracts/SwapFactory.sol, contracts/Swaplace.sol, contracts/interfaces/IErrors.sol, test/TestSwaplace.test.ts, test/TestTradeFactory.test.ts, test/utils/SwapFactory.ts
- changed InvalidExpiryDate into InvalidExpiry in all sources of the repo
=> refactor: InvalidExpiryDate custom error into InvalidExpiry only

contracts/SwapFactory.sol, contracts/interfaces/ISwapFactory.sol
- moved the SwaplaceFactory.sol NatSpec into ISwaplaceFactory.sol
- added a path to the ISwapFactory.sol from SwapFactory.sol
close #50
=> docs: fixed swaplace factory misplaced natspec

contracts/Swaplace.sol, contracts/interfaces/ISwaplace.sol
- migrated the natspec from Swaplace.sol into ISwaplace.sol
- Referenced the interface on the main contract
close #65
=> docs: changed natspec to the correct format

contracts/interfaces/ISwaplace.sol
- removed the interface as intended
- fixed spaces in the comment of other functions
close #67
=> fix: remove supportsInterface from the ISwaplace.sol

contracts/interfaces/ISwapFactory.sol
=> docs: create a title for ISwaplace.sol

contracts/Swaplace.sol
- removed the IERC20 import
- ninja patched supportsInterface
=> fix: the unnecessary IERC20 importation

contracts/Swaplace.sol, contracts/interfaces/ISwaplace.sol
- added the variables natspec as requested
- added an extra note in the getSwap, explaining how to check for non-existant swaps
fix #69
=> docs: add comment to variable

contracts/interfaces/ITransfer.sol
=> docs: enhance ITransfer.sol NatSpec comments

contracts/Swaplace.sol, contracts/interfaces/ISwaplace.sol
=> feat: create event logs for each function

.env.sample, hardhat.config.ts
=> feat: set default providers for EVM networks

test/TestSwaplace.test.ts
- added a deployer
- made the owner connect to the contract
- fixed some white spaces
close #41
=> refactor: deployer as signer and impacts

contracts/interfaces/IErrors.sol
=> docs: title for errors interface

contracts/interfaces/ISwap.sol, test/utils/SwapFactory.ts
- added natspec for the swaps
- removed the explanation on the swapFactory.ts
resolves #64
=> docs: ISwap.sol needs NatSpec comments

contracts/Swaplace.sol, contracts/interfaces/ISwaplace.sol
- added return true
- added boolean type in main Swaplace contract and in ISwaplace
close #88
=> feat: accept swap should return a boolean

.env.sample, contracts/Swaplace.sol, contracts/interfaces/ISwaplace.sol, contracts/mock/MockERC20.sol, contracts/mock/MockERC721.sol, scripts/acceptSwap.ts, scripts/cancelSwap.ts, scripts/createSwap.ts, scripts/deploy.ts, scripts/getSwap.ts, test/TestMockContracts.test.ts, test/TestSwapFactory.test.ts, test/TestSwaplace.test.ts, test/utils/SwapFactory.ts, test/utils/utils.ts
Refactored the entire test scope to be more cohesive and easy to understand, among other features listed in the commits
resolve #20 
resolve #94
=> test: change the context of the tests to be individual and not linear nor correlated

test/TestSwaplace.test.ts
- was missing tests for the `allowed` variable of the Swap struct
- removed unnecessary tests for fetching swaps
=> refactor: useless tests and new tests

contracts/SwapFactory.sol, contracts/Swaplace.sol, contracts/interfaces/ISwap.sol, contracts/interfaces/ISwaplace.sol, contracts/interfaces/ITransfer.sol, test/TestSwaplace.test.ts
- audited every file (overlooked in 1h)
- fixed a lot of grammar and references
=> fix: overall audit revealed doc missing

scripts/createSwap.ts, scripts/deploy.ts
I found that the `utils` path was wrong in `createSwap.ts` and `deploy.ts` so I corrected it.
=>   utils path corrected on scripts

.gitignore, Audit.md, contracts/echidna/TestSwapFactory.sol, contracts/echidna/TestSwaplace.sol, echidna_config.yaml, package.json
- added echidna config
- added tests for every functionality
- created scripts
- prepared md file with instructions on usage
close #93
=> feat: echidna test suit for fuzz coverage

contracts/mock/ERC20/ERC20.sol, contracts/mock/ERC20/interfaces/IERC20.sol, contracts/mock/ERC20/interfaces/IERC20Errors.sol, contracts/mock/ERC20/interfaces/IERC20Permit.sol
Hey @0xneves, 
- Set pragma versions of all files present in mock/ERC20 directory according to the version set in hardhat config.
- Closes #126 [](url)
=>  Wrong pragma versions #126 

hardhat.config.ts
Main purpose is to trigger the fuzz
=> feat: adding fantom network

.github/workflows/fuzz-testing.yml, .github/workflows/tests.yml
=> fix: moving from secrets into vars

CONTRIBUTING.md
=> feat: CONTRIBUTING.md

.env.sample, hardhat.config.ts
- removed swap creator and acceptee wallets for now
- updating .env.sample to a recent deployed instance of swaplace in sepolia
=> refactor: adding ternary in deployer key to aid github actions

CONTRIBUTING.md, README.md
Corrected some typos and grammatical errors, and rephrased a couple of sentences for better clarity.
closes #167
=>  docs: typos and grammatical errors. #167 

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/refactor-template.md
=> chore: fix issues template

contracts/Swaplace.sol, contracts/interfaces/ISwaplace.sol, test/TestSwaplace.test.ts
=> refactor: lower gas cost of createSwap by delegating security checks to the implementer #172

contracts/Swaplace.sol
Refactor this suggestion: https://github.com/blockful-io/swaplace-contracts/pull/188#discussion_r1476535635
=> Suggestion: Refactor emit swap canceled to use msg.sender to spend less gas

contracts/SwapFactory.sol, contracts/echidna/TestSwapFactory.sol, contracts/interfaces/ISwap.sol, contracts/interfaces/ISwapFactory.sol, contracts/interfaces/ISwaplace.sol, docs/solidity-docgen/SwapFactory.md, docs/solidity-docgen/Swaplace.md, docs/solidity-docgen/interfaces/IERC165.md, docs/solidity-docgen/interfaces/IErrors.md, docs/solidity-docgen/interfaces/ISwap.md, docs/solidity-docgen/interfaces/ISwapFactory.md, docs/solidity-docgen/interfaces/ISwaplace.md, docs/solidity-docgen/interfaces/ITransfer.md, docs/solidity-docgen/mock/ERC20/ERC20.md, docs/solidity-docgen/mock/ERC20/interfaces/IERC20.md, docs/solidity-docgen/mock/ERC20/interfaces/IERC20Errors.md, docs/solidity-docgen/mock/ERC20/interfaces/IERC20Permit.md, docs/solidity-docgen/mock/MockERC20.md, docs/solidity-docgen/mock/MockERC721.md, scripts/createSwap.ts, scripts/deployMock.ts, test/TestSwapFactory.test.ts, test/TestSwaplace.test.ts, test/utils/utils.ts
Ninja patched all the misplaced characters and some documentation issues before our release.
=> refactor: linting all files and updating solidity-docgen

contracts/Swaplace.sol
=>  Smart Contract Issues #193 

test/TestSwapFactory.test.ts
=> test: Unit tests for building native ether transfers 

contracts/Swaplace.sol
=> Changed the value from uint56 to uint256

contracts/echidna/TestSwapFactory.sol, test/TestSwapFactory.test.ts
=> test: Created unit tests to build ERC1155 assets 
